### ISSUE TITLE
No enterprise_extensions.setup_sampler in model_utils

### ISSUE THREAD

**Issue by kayhangultekin** [nanograv/dwg_tutorials#2]
I get an error when running the last part of `gwa_tutorial.ipynb `"Now, the easy way to do all of this" during the sampler_setup step that `model_utils` doesn't have setup_sampler.
```python
# Setup a sampler instance.
# This will add some fanicer stuff than before, like prior draws, 
# and custom sample groupings.
sampler = model_utils.setup_sampler(pta, outdir=outdir, resume=False)
```

If I replace `model_utils` with `sampler` and import `sampler` from `enterprise_extensions` earlier, then it works. I found this by grepping in `enterprise_exentions`, so I don't know if this is the Right Thing To Do. There is also a `sampler_setup` in `hypermodel`.

**Comment by kayhangultekin** [comment]
I made a pull request for my fix: #3

**Comment by stevertaylor** [comment]
Thanks @kayhangultekin. There were some API changes to enterprise_extensions which are probably being reflected here.

**Comment by stevertaylor** [comment]
Your fix looks good for this notebook, @kayhangultekin . The `hypermodel` `sampler_setup`is more relevant to model selection analyses in the second notebook.
