### ISSUE TITLE
dm_gp isn't defined in gwa_tutorial_part2.ipynb

### ISSUE THREAD

**Issue by kayhangultekin** [nanograv/dwg_tutorials#4]
The following cell in `gwa_tutorial_part2.ipynb` gives an error that `dm_gp` isn't defined:
```python
# full model
if bayesephem:
    s = ef + eq + rn + dm_gp + tm + eph + gw
else:
    s = ef + eq + rn + dm_gp + tm + gw
```

`log10_A_dm` and `gamma_dm` are both defined, so presumably, there should have been something above to the effect of:
```python
dm = utils.powerlaw(log10_A=log10_A_dm, gamma=gamma_dm)
dm_gp = gp_signals.FourierBasisGP(spectrum=dm, components=30, Tspan=Tspan, name='dm')
```
or else not include `dm_gp` in the `s = ...` line.

Also, @stevertaylor, would it be more efficient to create a dwg-tutorials channel on slack for this kind of thing?

**Comment by stevertaylor** [comment]
Another good catch @kayhangultekin. This is a holdover from adapting this notebook from the one I made for the IPTA. The other PTAs don't use DMX to model DM variations, so we have to model it there using Gaussian processes. But we can safely remove `dm_gp` from the model construction here. Would you mind making a PR for this?
